/**
 * Regenerates `src/symbols/lucide.generated.ts` from the installed
 * `lucide-static` package. Run with `pnpm tsx scripts/build-icons.ts`
 * (or `pnpm generate`).
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LUCIDE_IDS } from '../src/symbols/curated.js';
import { lucideVersion, readLucideBodies } from './lib/extract-lucide.js';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(packageRoot, 'src', 'symbols', 'lucide.generated.ts');

const bodies = readLucideBodies(LUCIDE_IDS);
const version = lucideVersion();

const entries = Object.entries(bodies)
  .map(([id, body]) => `  '${id}': '${body.replaceAll("'", "\\'")}',`)
  .join('\n');

const source = `// generated by scripts/build-icons.ts, do not edit
// source: lucide-static ${version} (ISC)

export const LUCIDE_VERSION = '${version}';

export const LUCIDE_SYMBOLS: Record<string, string> = {
${entries}
};
`;

writeFileSync(outFile, source, 'utf8');
console.log(`build-icons: wrote ${Object.keys(bodies).length} icons from lucide-static ${version}`);
