/**
 * The curated subset of the Lucide icon set used as person marks.
 *
 * Selection rules: recognisable at 4-5.5 mm on paper with a 0.4 mm stroke, so
 * nothing with more than about six separate strokes and nothing built from
 * hairline detail. Ids are kept sorted alphabetically.
 */
export const LUCIDE_IDS = [
  'anchor',
  'apple',
  'bike',
  'bird',
  'book',
  'bot',
  'bus',
  'candy',
  'car',
  'cat',
  'cherry',
  'cloud',
  'crown',
  'dice-5',
  'dog',
  'drum',
  'fish',
  'flame',
  'flower',
  'footprints',
  'gamepad-2',
  'ghost',
  'gift',
  'glasses',
  'guitar',
  'hammer',
  'heart',
  'house',
  'ice-cream-cone',
  'leaf',
  'lollipop',
  'medal',
  'moon',
  'mountain-snow',
  'music',
  'pizza',
  'plane',
  'puzzle',
  'rabbit',
  'rainbow',
  'rocket',
  'sailboat',
  'shell',
  'shield',
  'ship',
  'smile',
  'snail',
  'squirrel',
  'star',
  'sun',
  'sword',
  'tractor',
  'train-front',
  'tree-pine',
  'trophy',
  'turtle',
  'umbrella',
  'users',
  'wand-sparkles',
  'wrench',
  'zap',
] as const;

export type LucideId = (typeof LUCIDE_IDS)[number];
