import type { SymbolId } from './index.js';

export interface SymbolLabel {
  en: string;
  sv: string;
}

/**
 * Human labels for the legend and the symbol picker. `Record<SymbolId, ...>`
 * on purpose: adding a symbol without a label is a compile error.
 */
export const SYMBOL_LABELS: Record<SymbolId, SymbolLabel> = {
  anchor: { en: 'Anchor', sv: 'Ankare' },
  apple: { en: 'Apple', sv: 'Äpple' },
  bike: { en: 'Bicycle', sv: 'Cykel' },
  bird: { en: 'Bird', sv: 'Fågel' },
  book: { en: 'Book', sv: 'Bok' },
  bot: { en: 'Robot', sv: 'Robot' },
  bus: { en: 'Bus', sv: 'Buss' },
  candy: { en: 'Candy', sv: 'Godis' },
  car: { en: 'Car', sv: 'Bil' },
  cat: { en: 'Cat', sv: 'Katt' },
  cherry: { en: 'Cherries', sv: 'Körsbär' },
  cloud: { en: 'Cloud', sv: 'Moln' },
  crown: { en: 'Crown', sv: 'Krona' },
  'dice-5': { en: 'Dice', sv: 'Tärning' },
  dinosaur: { en: 'Dinosaur', sv: 'Dinosaurie' },
  dog: { en: 'Dog', sv: 'Hund' },
  drum: { en: 'Drum', sv: 'Trumma' },
  'firefighter-helmet': { en: 'Fire helmet', sv: 'Brandhjälm' },
  fish: { en: 'Fish', sv: 'Fisk' },
  flame: { en: 'Flame', sv: 'Låga' },
  flower: { en: 'Flower', sv: 'Blomma' },
  footprints: { en: 'Footprints', sv: 'Fotspår' },
  'gamepad-2': { en: 'Game controller', sv: 'Spelkontroll' },
  ghost: { en: 'Ghost', sv: 'Spöke' },
  gift: { en: 'Present', sv: 'Present' },
  glasses: { en: 'Glasses', sv: 'Glasögon' },
  guitar: { en: 'Guitar', sv: 'Gitarr' },
  hammer: { en: 'Hammer', sv: 'Hammare' },
  heart: { en: 'Heart', sv: 'Hjärta' },
  house: { en: 'House', sv: 'Hus' },
  'ice-cream-cone': { en: 'Ice cream', sv: 'Glass' },
  leaf: { en: 'Leaf', sv: 'Löv' },
  lollipop: { en: 'Lollipop', sv: 'Klubba' },
  medal: { en: 'Medal', sv: 'Medalj' },
  moon: { en: 'Moon', sv: 'Måne' },
  'mountain-snow': { en: 'Mountain', sv: 'Berg' },
  music: { en: 'Music', sv: 'Musik' },
  pizza: { en: 'Pizza', sv: 'Pizza' },
  plane: { en: 'Aeroplane', sv: 'Flygplan' },
  puzzle: { en: 'Puzzle piece', sv: 'Pusselbit' },
  rabbit: { en: 'Rabbit', sv: 'Kanin' },
  rainbow: { en: 'Rainbow', sv: 'Regnbåge' },
  rocket: { en: 'Rocket', sv: 'Raket' },
  sailboat: { en: 'Sailing boat', sv: 'Segelbåt' },
  shell: { en: 'Shell', sv: 'Snäcka' },
  shield: { en: 'Shield', sv: 'Sköld' },
  ship: { en: 'Ship', sv: 'Skepp' },
  smile: { en: 'Smiley', sv: 'Smiley' },
  snail: { en: 'Snail', sv: 'Snigel' },
  squirrel: { en: 'Squirrel', sv: 'Ekorre' },
  star: { en: 'Star', sv: 'Stjärna' },
  sun: { en: 'Sun', sv: 'Sol' },
  sword: { en: 'Sword', sv: 'Svärd' },
  tiara: { en: 'Tiara', sv: 'Tiara' },
  tractor: { en: 'Tractor', sv: 'Traktor' },
  'train-front': { en: 'Train', sv: 'Tåg' },
  'tree-pine': { en: 'Pine tree', sv: 'Gran' },
  trophy: { en: 'Trophy', sv: 'Pokal' },
  turtle: { en: 'Turtle', sv: 'Sköldpadda' },
  umbrella: { en: 'Umbrella', sv: 'Paraply' },
  unicorn: { en: 'Unicorn', sv: 'Enhörning' },
  users: { en: 'Group', sv: 'Grupp' },
  'wand-sparkles': { en: 'Magic wand', sv: 'Trollstav' },
  wrench: { en: 'Spanner', sv: 'Skiftnyckel' },
  zap: { en: 'Lightning', sv: 'Blixt' },
};
