<script setup lang="ts">
import { t } from '../../i18n/index.js';

/**
 * The preview is the sheet itself: the same SVG the printer gets, scaled to the
 * pane. Because the renderer emits absolute millimetres there is nothing to
 * diverge between what is shown here and what comes out of the printer.
 */
defineProps<{
  svg: string;
}>();
</script>

<template>
  <div class="stage">
    <figure class="sheet" :aria-label="t('builder.previewTitle')">
      <!-- eslint-disable-next-line vue/no-v-html -- generated by the renderer, not user input -->
      <div class="paper" v-html="svg" />
    </figure>
  </div>
</template>

<style scoped>
.stage {
  height: 100%;
  overflow: auto;
  display: grid;
  place-items: center;
  padding: var(--space-5);
  background: var(--desk);
}

/*
 * The whole page has to be visible at a glance. A percentage height would need
 * an unbroken chain of definite heights up to the viewport, which the panel
 * layout does not guarantee, so the sheet is bounded against the viewport
 * directly: everything above it is a known height.
 */
.sheet {
  --chrome: calc(var(--header-height) + 2 * var(--space-5));
  margin: 0;
  display: flex;
  justify-content: center;
  max-width: min(100%, 760px);
}

.paper {
  background: var(--white);
  box-shadow: var(--shadow-sheet);
}

.paper :deep(svg) {
  display: block;
  width: auto;
  height: auto;
  max-width: 100%;
  max-height: calc(100vh - var(--chrome));
}

@media (max-width: 900px) {
  .stage {
    padding: var(--space-4);
    place-items: start center;
  }

  .paper :deep(svg) {
    width: 100%;
    max-height: none;
  }
}
</style>
