<script setup lang="ts">
import { t } from '../../i18n/index.js';

/**
 * The preview is the sheet itself: the same SVG the printer gets, scaled to the
 * pane. Because the renderer emits absolute millimetres there is nothing to
 * diverge between what is shown here and what comes out of the printer.
 */
defineProps<{
  svg: string;
}>();
</script>

<template>
  <div class="stage-scroll">
    <figure class="sheet" :aria-label="t('builder.previewTitle')">
      <!-- eslint-disable-next-line vue/no-v-html -- generated by the renderer, not user input -->
      <div class="paper" v-html="svg" />
    </figure>
  </div>
</template>

<style scoped>
/*
 * The whole page has to be visible at a glance. The stage is a flex column
 * whose middle row gets a definite height, so the sheet can be bounded as a
 * percentage of the space actually left rather than by guessing at the chrome.
 */
.stage-scroll {
  overflow: auto;
  display: grid;
  place-items: center;
  padding: 32px var(--space-5) 20px;
}

.sheet {
  margin: 0;
  display: flex;
  justify-content: center;
  max-width: min(100%, 520px);
  max-height: 100%;
  min-height: 0;
}

.paper {
  background: var(--white);
  box-shadow: var(--shadow-sheet);
  min-height: 0;
}

.paper :deep(svg) {
  display: block;
  width: auto;
  height: auto;
  max-width: 100%;
  max-height: 100%;
}

@media (max-width: 900px) {
  .stage-scroll {
    padding: var(--space-4);
    place-items: start center;
  }

  .sheet {
    max-height: none;
  }

  .paper :deep(svg) {
    width: 100%;
  }
}
</style>
